spring.application.name=Healthcare-Appointment-Management-System

spring.datasource.url=jdbc:mysql://localhost:3306/healthcare_appointment_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=healthcare-secret-key-123456789-healthcare
jwt.expiration=3600000

# Cloudinary SDK for Java
cloudinary.cloud-name=ddk69izjd
cloudinary.api-key=135916851499558
cloudinary.api-secret=9t3VzkD19UHvs3Sc3V9FrpgU9vk

# Default Doctor Image URL
cloudinary.default-doctor-image=https://res.cloudinary.com/ddk69izjd/image/upload/v1766830431/default_aqre5v.jpg

# Sending Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jasphinvijayj@gmail.com
spring.mail.password=znpv nwms cchj abeb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true